# Generated by Django 5.1.6 on 2025-03-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default=True, upload_to='uploads/'),
        ),
    ]
